# Ensure that the plugin meets the required style guidelines
# Ensure that the plugin builds correctly

name: CI Checks

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.11

      - name: Install Deps
        run: |
          pip install -U wheel setuptools twine build
      - name: Build Plugin
        run: |
          python -m build

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "20"

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run translate
          npm run build
          npm run lint

  backend:
    name: "Style: python"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"

      - name: Install style check dependencies
        run: |
          pip install -U ruff

      - name: Style Checks
        run: |
          ruff check
